added data efficiency experiments on segmentation
JanEGerken/HEAL-SWIN pull request #1
Opened 2023-07-25 13:00 UTC by h-spiess

this adds the code that enables training on a subset of the training data and adds two default configs for the flat and hp models

2023-07-25 13:01 UTC, h-spiess commented
in addition, it fixed the default flat configs

2023-08-03 07:00 UTC, JanEGerken requested changes
Good work, thanks Heiner! Could you remove argparse from the config files? I left a comment there. Also, could you add a few lines describing the new config files in `heal_swin/README.md` in the "Reproducing runs from the paper" section under "segmentation"? Apart from that, please run black and flake8 and we're good to go.

2023-08-03 07:00 UTC, JanEGerken commented on heal_swin/run_configs/segmentation/data_efficiency_swin_hp_synwoodscape_large_plus_AD_train_run_config.py
> +def get_argparser_for_config_args():
This goes a bit against our philosophy of only using config files and staying away from argparse as much as possible. Could you refactor this to be used as an array job, similarly to our evaluation config files? Then, the range of fractions and the seed are also documented here. For array jobs, you also have to change the naming of the slurm file in line 4 and the `job_id` should contain the task number in line 43.

2023-08-03 07:00 UTC, JanEGerken commented on heal_swin/run_configs/segmentation/data_efficiency_swin_synwoodscape_large_plus_AD_train_run_config.py
> +def get_argparser_for_config_args():
See above

2023-08-17 12:02 UTC, h-spiess commented
i think i have addressed these issues with the new commit

2023-08-18 09:17 UTC, JanEGerken requested changes
Great, thanks for updating the readme and the run configs!
I think you ran black with the default line length instead of the line length 100 which we use in this repo. Could you rerun black with the longer line length, e.g. by using `format-code` from `run.py`? Please also check the diffs, sometimes, black introduces commas when it shrinks lines which prevent them from being enlarged later.

2023-08-18 15:38 UTC, h-spiess commented
okay. i've changed by black settings to not have that issue in the future and i've run `format-code`.

2023-08-18 18:51 UTC, JanEGerken approved these changes
Perfect, thanks!

2023-08-18 18:53 UTC, merged